### ISSUE TITLE
Неверное название кнопки

### ISSUE THREAD

**Issue by OlgaTester** [UnickSoft/FreeLingua#2]
Неверное название кнопки для функции добавления задания. Звучит двусмыленно. Вместо "Check right answer" нужно "Enter question
![Снимок экрана 2021-11-09 в 21 57 57](https://user-images.githubusercontent.com/94014331/140995739-55a68c1a-ef99-444b-8dc8-1ffd787029c5.png)
".

**Comment by UnickSoft** [comment]
Исправлено, просьба перепроверить и закрыть.
