### ISSUE TITLE
Неверное названия поля ввода пароля при входе в личный кабинет

### ISSUE THREAD

**Issue by OlgaTester** [UnickSoft/FreeLingua#4]
Неверное название поля ввода пароля, вместо "Enter email" нужно "Enter password
![Снимок экрана 2021-11-09 в 22 02 47](https://user-images.githubusercontent.com/94014331/140996799-39b1f28d-60a2-41dd-ac76-543528bed7a0.png)
".

**Comment by UnickSoft** [comment]
Исправлено, просьба перепроверить и закрыть.
