### ISSUE TITLE
Не работают кнопки Move Up, Move down

### ISSUE THREAD

**Issue by OlgaTester** [UnickSoft/FreeLingua#5]
В разделе Add Task Не работают кнопки Move Up, Move down.
![Снимок экрана 2021-11-09 в 22 11 16](https://user-images.githubusercontent.com/94014331/140997367-a5b3d384-1da9-4e8b-a281-69b2c5296b22.png)

**Comment by UnickSoft** [comment]
Исправлено, просьба перепроверить и закрыть.
