### ISSUE TITLE
Сервис сохраняет задание с незаполненным последним вопросом 

### ISSUE THREAD

**Issue by OlgaTester** [UnickSoft/FreeLingua#6]
Сервис сохраняет задание с незаполненным последним вопросом и при выборе во вкладке Test отправляет на пустую страницу.
![Снимок экрана 2021-11-09 в 22 13 50](https://user-images.githubusercontent.com/94014331/140998041-633741b4-0e51-4589-92d7-5f806a324a89.png)

**Comment by UnickSoft** [comment]
Исправлено, просьба перепроверить и закрыть.
