### ISSUE TITLE
Нет возможности создать второе задание в типе заданий "fill (in) the gaps"

### ISSUE THREAD

**Issue by OlgaTester** [UnickSoft/FreeLingua#8]
Нет возможности создать второе задание в типе заданий "fill (in) the gaps". При выделении слова и нажатии "Add gap" ничего не происходит.
![Снимок экрана 2021-12-14 в 21 02 48](https://user-images.githubusercontent.com/94014331/146063502-f16927ae-7ce0-4742-b471-042c7969357c.png)

**Comment by UnickSoft** [comment]
Исправлено. Необходимо протестировать и закрыть.

**Comment by UnickSoft** [comment]
update
